# Generated by Django 4.2.4 on 2023-08-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author'),
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='books',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
