# Generated by Django 4.2.4 on 2023-08-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_photo'),
        ('readers', '0002_reader_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='books',
            field=models.ManyToManyField(null=True, to='books.book'),
        ),
    ]
