# Generated by Django 4.2.4 on 2023-08-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_photo'),
        ('readers', '0003_alter_reader_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='books',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
